### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by DidntRead** [DidntRead/android_device_A7010a48#2]
- [x] Bringup
    - [x] Surfaceflinger
    - [x] Adbd
    - [x] Boots to lockscreen
- [x] Basic functionality
    - [x] Telephony (Fixed by DidntRead/android_vendor_A7010a48@ef65feee7f73f65e560ec73a4e74ca8a70dc259b)
    - [x] Wifi
    - [x] Audio  (Fixed by DidntRead/android_vendor_A7010a48@8d191b17e757922f681a3c5924dac979358e35d6)
        - [x] Out
        - [x] In
        - [x] Bluetooth

- [ ] HALs
    - [x] Biometrics
    - [ ] GNSS/GPS
    - [x] BroadcastRadio
    - [x] Bluetooth
    - [x] DRM
    - [x] OMX
    - [x] Camera (Video recording works with sw codecs)
        - [x] Flashlight/Torch
        - [x] Pictures
        - [ ] Video
    - [x] Sensor
    - [x] Vibrator
    - [x] Light
    - [ ] NFC

- [x] Extras
    - [x] Power off charging
    - [ ] Power off alarm
    - [ ] Volte

- [ ] Final adjustments
    - [ ] Enforcing selinux
    - [ ] Upstreamed kernel

**Comment by sai-vitu** [comment]
ansioso por essa rom <3
